<?php

/**
 * @file
 * Contains simple_styleguide.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function simple_styleguide_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the simple_styleguide module.
    case 'help.page.simple_styleguide':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('TODO') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function simple_styleguide_theme() {
  return [
    'simple_styleguide' => [
      'template' => 'simple_styleguide',
      'render element' => 'children',
    ],
  ];
}
