simple_styleguide.styleguide_snippet.*:
  type: config_entity
  label: 'Styleguide snippet config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    snippet:
      type: string
      label: 'Snippet'
    uuid:
      type: string
