simple_styleguide.styleguide_pattern.*:
  type: config_entity
  label: 'Styleguide pattern config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    pattern:
      type: string
      label: 'Pattern'
    uuid:
      type: string
